openapi: 3.0.1
info:
  title: Arlington Vote Transparency
  description: 'This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  version: 1.0.0
tags:
- name: avt
  description: Arlington Vote Transparency
paths:
  /vote-history:
    get:
      tags:
      - avt
      parameters:
        - name: precinct
          in: query
          description: User's precinct number
          schema:
            type: integer
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/VoteHistoryResponse'
components:
  schemas:
    VoteHistoryResponse:
      type: object
      properties:
        articles:
          description: abc
          type: array
          items:
            $ref: '#/components/schemas/Article'
    Article:
      type: object
      properties:
        name:
          type: string
        amendments:
          type: array
          items:
            $ref: '#/components/schemas/Amendment'
        voteRecords:
          type: array
          items:
            $ref: '#/components/schemas/Vote'
    Amendment:
      type: object
      properties:
        name:
          type: string
        voteRecords:
          type: array
          items:
            $ref: '#/components/schemas/Vote'
    Vote:
      type: object
      properties:
        precinct:
          type: integer
        representativeFullName:
          type: string
        vote:
          enum:
          - 'yes'
          - 'no'
          - 'abstain'
        date:
          type: string
          format: date
        
    
